/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as CharacterCreateRouteImport } from './routes/character/create'
import { Route as CharacterViewIndexRouteImport } from './routes/character/view/index'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'
import { Route as CharacterViewIdRouteImport } from './routes/character/view/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const CharacterCreateRoute = CharacterCreateRouteImport.update({
  id: '/character/create',
  path: '/character/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CharacterViewIndexRoute = CharacterViewIndexRouteImport.update({
  id: '/character/view/',
  path: '/character/view/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)
const CharacterViewIdRoute = CharacterViewIdRouteImport.update({
  id: '/character/view/$id',
  path: '/character/view/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/character/create': typeof CharacterCreateRoute
  '/demo/table': typeof DemoTableRoute
  '/character/view/$id': typeof CharacterViewIdRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/character/view/': typeof CharacterViewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/character/create': typeof CharacterCreateRoute
  '/demo/table': typeof DemoTableRoute
  '/character/view/$id': typeof CharacterViewIdRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/character/view': typeof CharacterViewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/character/create': typeof CharacterCreateRoute
  '/demo/table': typeof DemoTableRoute
  '/character/view/$id': typeof CharacterViewIdRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/character/view/': typeof CharacterViewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/character/create'
    | '/demo/table'
    | '/character/view/$id'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/character/view/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/character/create'
    | '/demo/table'
    | '/character/view/$id'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/character/view'
  id:
    | '__root__'
    | '/'
    | '/character/create'
    | '/demo/table'
    | '/character/view/$id'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/character/view/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CharacterCreateRoute: typeof CharacterCreateRoute
  DemoTableRoute: typeof DemoTableRoute
  CharacterViewIdRoute: typeof CharacterViewIdRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
  CharacterViewIndexRoute: typeof CharacterViewIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/character/create': {
      id: '/character/create'
      path: '/character/create'
      fullPath: '/character/create'
      preLoaderRoute: typeof CharacterCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/character/view/': {
      id: '/character/view/'
      path: '/character/view'
      fullPath: '/character/view/'
      preLoaderRoute: typeof CharacterViewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/character/view/$id': {
      id: '/character/view/$id'
      path: '/character/view/$id'
      fullPath: '/character/view/$id'
      preLoaderRoute: typeof CharacterViewIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CharacterCreateRoute: CharacterCreateRoute,
  DemoTableRoute: DemoTableRoute,
  CharacterViewIdRoute: CharacterViewIdRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
  CharacterViewIndexRoute: CharacterViewIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
